apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: gloo-rest-soap-transformation
  name: gloo-rest-soap-transformation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gloo-rest-soap-transformation
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gloo-rest-soap-transformation
    spec:
      containers:
      - image: simongreen02/calypso:gloo-rest-soap-transformation
        name: gloo-rest-soap-transformation
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: gloo-rest-soap-transformation
  name: gloo-rest-soap-transformation
spec:
  type: LoadBalancer
  selector:
    app: gloo-rest-soap-transformation
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
status:
  loadBalancer: {}